# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('age', models.IntegerField(default='')),
                ('professional_status', models.CharField(choices=[('developer', 'Developer'), ('juniordeveloper', 'Junior Developer'), ('seniordeveloper', 'Senior Developer'), ('manager', 'Manager'), ('ceo', 'CEO'), ('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('instructor', 'Instructor or Teacher'), ('intern', 'Intern'), ('employee', 'Employee'), ('freelancer', 'Freelancer'), ('work', 'Work'), ('other', 'Other')], default='', max_length=450)),
                ('company', models.CharField(default='', max_length=70)),
                ('website', models.URLField(default='')),
                ('location', models.CharField(default='', max_length=250)),
                ('skills', models.CharField(default='', max_length=450)),
                ('github_username', models.URLField(default='')),
                ('short_bio', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('london', django.db.models.manager.Manager()),
            ],
        ),
    ]
